# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  perhaps-benchmarks:
    dependencies:
    - base
    - perhaps
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: perhaps is a new Haskeleton package.
executables:
  perhaps:
    dependencies:
    - base
    - perhaps
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: 
github: mrkgnao/perhaps
library:
  dependencies:
  - base
  - mtl
  - containers
  source-dirs: library
license: MIT
maintainer: Soham Chowdhury
name: perhaps
synopsis: A new Haskeleton package.
tests:
  perhaps-test-suite:
    dependencies:
    - base
    - perhaps
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
